### ISSUE TITLE
`Kernel minimum runtime larger than default TDR` when running expensive hash

### ISSUE THREAD

**Issue by lhunath** [hashcat/hashcat#2758]
Running hashcat against an expensive hash such as scrypt with costly parameters causes hashcat to fail with:
```
Kernel minimum runtime larger than default TDR
```
It appears this is caused by a fairly arbitrary(?) check here:
https://github.com/hashcat/hashcat/blob/c3c315b170aadd937ec080c57fff2e960d6eac2d/src/autotune.c#L211-L216

Disabling the code causes hashcat to proceed and succeed with the operation just fine.  It's unclear why this check is here, what `2000` is referencing and what "the default TDR" is.

Seems to be introduced by: https://github.com/hashcat/hashcat/commit/73bba00286d815878b544d2d0aa6a79e6cf698ce

**Comment by jsteube** [comment]
The 2000 was the default value (in ms) from the driver on windows, thus the hardcode. This should also be fixed with the other commit we talked about.

**Comment by jsteube** [comment]
With this commit https://github.com/hashcat/hashcat/commit/15f35fa68c1d598eb9e56e700716b444a944b074 I think I solved the problem with very long kernel runtimes. There's still the chance for the init kernel to cause a kernel runtime but this would need super high N values (> 1M). Please retry and close the issue if fixed.

**Comment by jsteube** [comment]
OP please update

**Comment by lhunath** [comment]
The problem no longer occurs. Still having a hardcoded maximum runtime seems unnecessary when commenting it out allowed me to proceed successfully.

**Comment by jsteube** [comment]
But that shouldn't happen anymore because of the refactorization. So this section today is more like a nice hint for us that if it occurs to someone, that we need to fix something we didn't think of.
