### ISSUE TITLE
Hashcat 6.2.4 problem with DES (Unix)

### ISSUE THREAD

**Issue by kerszl** [hashcat/hashcat#2996]
**Describe the bug**
When cracking DES (Unix) Hashes , Hashcat 6.2.4 throws me an error. But version 6.2.3 works fine with that.

**Expected behavior**
Work

**Hardware/Compute device (please complete the following information):**
- Compute device name: Radeon (TM) RX 470 Graphics
- OpenCL/CUDA driver name: OpenCL C 2.0
- OpenCL/CUDA driver version: 3075.13

**Hashcat version (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

**Additional context**
```
Below examples from both versions:

PS C:\temp\hashcat-6.2.3> .\hashcat.exe -O -a0 -m1500 .\crack\hashe.txt .\wordlists\rockyou.txt
hashcat (v6.2.3) starting

OpenCL API (OpenCL 2.1 AMD-APP (3075.13)) - Platform #1 [Advanced Micro Devices, Inc.]
======================================================================================
* Device #1: Radeon (TM) RX 470 Graphics, 4032/4096 MB (3264 MB allocatable), 32MCU

OpenCL API (OpenCL 1.2 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #2: Intel(R) HD Graphics 4600, 1565/1629 MB (407 MB allocatable), 20MCU
* Device #3: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, skipped

Kernel ./OpenCL/m01500_a0-optimized.cl:
Optimized kernel requested, but not available or not required
Falling back to pure kernel

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 8

Hashes: 2 digests; 2 unique digests, 2 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Not-Iterated

Watchdog: Temperature abort trigger set to 90c

* Device #1: Skipping hash-mode 1500)
             This is due to a known CUDA/HIP/OpenCL runtime/driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.
Host memory required for this attack: 16 MB

Dictionary cache hit:
* Filename..: .\wordlists\rockyou.txt
* Passwords.: 14344385
* Bytes.....: 139921507
* Keyspace..: 14344385

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit =>

Session..........: hashcat
Status...........: Quit
Hash.Name........: descrypt, DES (Unix), Traditional DES
Hash.Target......: .\crack\hashe.txt
Time.Started.....: Thu Sep 23 16:15:41 2021 (3 secs)
Time.Estimated...: Thu Sep 23 16:18:38 2021 (2 mins, 54 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (.\wordlists\rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:   161.4 kH/s (10.01ms) @ Accel:16 Loops:1 Thr:8 Vec:1
Speed.#*.........:   161.4 kH/s
Recovered........: 0/2 (0.00%) Digests, 0/2 (0.00%) Salts
Progress.........: 545512/28688770 (1.90%)
Rejected.........: 105192/545512 (19.28%)
Restore.Point....: 271804/14344385 (1.89%)
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#2....: hill33 -> darius14
Hardware.Mon.#2..: N/A

Started: Thu Sep 23 16:15:40 2021
Stopped: Thu Sep 23 16:15:45 2021
PS C:\temp\hashcat-6.2.3>



PS C:\temp\hashcat-6.2.4> .\hashcat.exe -O -a0 -m1500 .\crack\hashe.txt .\wordlists\rockyou.txt
hashcat (v6.2.4) starting

hipFuncGetAttribute is missing from HIP shared library.

OpenCL API (OpenCL 2.1 AMD-APP (3075.13)) - Platform #1 [Advanced Micro Devices, Inc.]
======================================================================================
* Device #1: Radeon (TM) RX 470 Graphics, 3968/4096 MB (3264 MB allocatable), 32MCU

OpenCL API (OpenCL 1.2 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #2: Intel(R) HD Graphics 4600, 768/1629 MB (203 MB allocatable), 20MCU
* Device #3: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, skipped

Kernel ./OpenCL/m01500_a0-optimized.cl:
Optimized kernel requested, but not available or not required
Falling back to pure kernel

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 8

Hashes: 2 digests; 2 unique digests, 2 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Not-Iterated

Watchdog: Temperature abort trigger set to 90c

* Device #1: Skipping hash-mode 1500)
             This is due to a known CUDA/HIP/OpenCL runtime/driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.
* Device #2: Not enough allocatable device memory for this attack.

Started: Thu Sep 23 16:17:11 2021
Stopped: Thu Sep 23 16:17:14 2021
PS C:\temp\hashcat-6.2.4>
```

**Comment by oam7575** [comment]
Appears to be working fine on Win 10 with GTX 1660 Ti

There is output from your log that indicates a driver issue

**Device #1: Skipping hash-mode 1500)
             This is due to a known CUDA/HIP/OpenCL runtime/driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.
Device #2: Not enough allocatable device memory for this attack.**

1660 Ti Run below


> E:\hashcat\hashcat-6.2.4>hashcat.exe -O -a3 -m1500 ..\hash\des_1500.txt
> hashcat (v6.2.4) starting
> 
> CUDA API (CUDA 11.4)
> ====================
> * Device 1: NVIDIA GeForce GTX 1660 Ti, 5163/6144 MB, 24MCU
> 
> OpenCL API (OpenCL 3.0 CUDA 11.4.56) - Platform 1 [NVIDIA Corporation]
> =======================================================================
> * Device 2: NVIDIA GeForce GTX 1660 Ti, skipped
> 
> Kernel ./OpenCL/m01500_a3-optimized.cl:
> Optimized kernel requested, but not available or not required
> Falling back to pure kernel
> 
> Minimum password length supported by kernel: 0
> Maximum password length supported by kernel: 8
> 
> Hashes: 1 digests; 1 unique digests, 1 unique salts
> Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
> 
> Optimizers applied:
> * Zero-Byte
> * Not-Iterated
> * Single-Hash
> * Single-Salt
> * Brute-Force
> 
> Watchdog: Temperature abort trigger set to 90c
> 
> Host memory required for this attack: 2469 MB
> 
> The wordlist or mask that you are using is too small.
> This means that hashcat cannot use the full parallel power of your device(s).
> Unless you supply more work, your cracking speed will drop.
> For tips on supplying more work, see: https://hashcat.net/faq/morework
> 
> 
> ***Truncated***
> 
> 
> 48c/R8JAv757A:hashcat
> 
> Session..........: hashcat
> Status...........: Cracked
> Hash.Mode........: 1500 (descrypt, DES (Unix), Traditional DES)
> Hash.Target......: 48c/R8JAv757A
> Time.Started.....: Sun Sep 26 07:18:37 2021 (29 secs)
> Time.Estimated...: Sun Sep 26 07:19:06 2021 (0 secs)
> Kernel.Feature...: Pure Kernel
> Guess.Mask.......: ?1?2?2?2?2?2?2 [7]
> Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
> Guess.Queue......: 7/8 (87.50%)
> Speed.#1.........:   761.4 MH/s (7.74ms) @ Accel:2 Loops:1024 Thr:128 Vec:1
> Recovered........: 1/1 (100.00%) Digests
> Progress.........: 22272344064/134960504832 (16.50%)
> Rejected.........: 0/22272344064 (0.00%)
> Restore.Point....: 276480/1679616 (16.46%)
> Restore.Sub.#1...: Salt:0 Amplifier:8192-9216 Iteration:0-1024
> Candidate.Engine.: Device Generator
> Candidates.#1....: lnie2v1 -> Lurbaso
> Hardware.Mon.#1..: Temp: 54c Fan: 49% Util: 95% Core:1932MHz Mem:5745MHz Bus:16
> 
> Started: Sun Sep 26 07:18:12 2021
> Stopped: Sun Sep 26 07:19:07 2021
> 
> E:\hashcat\hashcat-6.2.4>

**Comment by kerszl** [comment]
Not only DES is not working on Hashcat 6.2.4. With (sha512crypt $6$, SHA512 (Unix)) is similiar problem.
I returned to version 6.2.3. It's working.

**Comment by jsteube** [comment]
I'm wondering why you use 6.2.3 and not the fixed beta? I think it was fixed a day after your report...

**Comment by kerszl** [comment]
Every program I downloaded from hashcat.net

https://hashcat.net/files/hashcat-6.1.1.7z
https://hashcat.net/files/hashcat-6.2.1.7z
https://hashcat.net/files/hashcat-6.2.3.7z
https://hashcat.net/files/hashcat-6.2.4.7z

**Comment by jsteube** [comment]
Betas can be found on https://hashcat.net/beta/

**Comment by kerszl** [comment]
![obraz](https://user-images.githubusercontent.com/45152848/135659907-45c0b9f5-6e33-4fcc-ab19-4bea08fd137b.png)
Still not work with beta version (22.09.2021) **hashcat-6.2.4+74.7z**

**Comment by jsteube** [comment]
Please retry with hashcat-6.2.5+35.7z

**Comment by mohemiv** [comment]
Same issue: https://github.com/hashcat/hashcat/issues/2986

**Comment by jsteube** [comment]
Could you please retry with hashcat v7.0.0 that was released few days ago? I've tested on a RX 480 and it worked, but I don't have a RX 470 for testing. You can also try with absolutest latest beta from https://hashcat.net/beta/
